
version: '3.1'
services:
  mongo:
    image: mongo:latest
    container_name: becoder_academy
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

